# Exercício de Programação 1

<font color="red">**Prazo de submissão: 23:55 do dia 19/03/2020** </font>

2020.1 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel$\rightarrow$Restart e então execute **todas as células** (no menu, Cell$\rightarrow$Run All)
* Apenas o arquivo .ipynb deve ser submetido. Ele não deve ser compactado.
* Não deixe de preencher seu nome e número de matrícula na célula a seguir

Nome do aluno: Victor Vieira de Melo

Matricula: 2019055028

## Parte 1: Python básico

In [1]:
# Exercício 1 - Imprima na tela os números de 1 a 10 e armazene-os em uma lista.
lista = []
for i in range(1,11):
    print(i)
    lista.append(i)
print(lista)

1
2
3
4
5
6
7
8
9
10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
# Exercício 2 - Crie duas strings e concatene as duas em uma terceira string
string1 = "ALC "
string2 = "é muito bom"
string3 = string1+string2
print(string3)

ALC é muito bom


In [3]:
# Exercício 3 - Crie uma tupla com os seguintes elementos: 1, 2, 2, 3, 4, 4, 4, 5 e depois utilize a função count do 
# objeto tupla para verificar quantas vezes o número 4 aparece na tupla
tupla = (1,2,2,3,4,4,4,5)
numero_de_4 = tupla.count(4)
print(numero_de_4)

3


In [4]:
# Exercício 4 - Crie um dicionário com 3 chaves e 3 valores e imprima na tela
dicionario = {"chave1":1,"chave2":2,"chave3":3}
print(dicionario)
print(dicionario["chave1"])
print(dicionario["chave2"])
print(dicionario["chave3"])

{'chave1': 1, 'chave2': 2, 'chave3': 3}
1
2
3


In [5]:
# Exercício 5 - Adicione mais um elemento ao dicionário criado no exercício anterior e imprima na tela
dicionario["chave4"] = 4
print(dicionario)
print(dicionario["chave1"])
print(dicionario["chave2"])
print(dicionario["chave3"])
print(dicionario["chave4"])

{'chave1': 1, 'chave2': 2, 'chave3': 3, 'chave4': 4}
1
2
3
4


In [6]:
# Exercício 6 - Crie um novo dicionário invertendo o anterior (isto é, usando os valores como chave e vice-versa)
invertido = {}
for i in range(1,5):
    invertido[i] = "chave"+str(i)
print(invertido)

{1: 'chave1', 2: 'chave2', 3: 'chave3', 4: 'chave4'}


In [7]:
# Exercício 7 - Crie uma função que receba uma string como argumento e retorne a mesma string em letras maiúsculas.
# Faça uma chamada à função, passando como parâmetro uma string
string = "ola mundo"
def uperstr(_str):
    super_string = _str.upper()
    return super_string
print(uperstr(string))

OLA MUNDO


In [8]:
# Exercício 8 - Crie uma função que receba como parâmetro uma lista de 4 elementos, adicione 2 elementos a lista e 
# imprima a lista. Esta função não deve retornar nada.
lista = [1,2,3,4]
def add_elemento(_list):
    _list.append(5)
    _list.append(6)

print(lista)
add_elemento(lista)
print(lista)

[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6]


In [9]:
# Exercício 9 - Faça a correção dos erros no código abaixo e execute o programa. Dica: são 3 erros.
temperatura = float(input('Qual a temperatura? '))
if temperatura > 30:
    print('Vista roupas leves.')
else:
    print('Busque seus casacos.')

Qual a temperatura? 50
Vista roupas leves.


In [10]:
# Exercício 10 - Crie uma função que conte quantas vezes a letra "r" aparece na frase abaixo. Use um placeholder (%) na 
# sua instrução de impressão
frase = "All models are wrong, but some are useful (George Box)"
def conta_r(_str):
    return _str.count('r')

print("A frase tem %.0f r's"% conta_r(frase))

A frase tem 4 r's


## Parte 2: numpy

## Questão 1

Crie as matrizes A, B e C abaixo e resolva as questões:
1. [ ] Calcule $(((A^T B)+B)C^{-1})$
2. [ ] Crie matrizes $\tilde A_{2x2}, \tilde B_{2x2}, \tilde C_{2x2}$, tal que sejam compostas pelo 2 primeiros elementos de cada linha das duas primeiras linhas. E repita a equação do item anterior.

**Dica** numpy.full, numpy.eye, numpy.ones e indexação de vetores.

$$
A = \begin{bmatrix}
 8 & 8 & 8\\
 8 & 8 & 8\\
 8 & 8 & 8
\end{bmatrix}_{3\times 3}
\qquad
B = \begin{bmatrix}
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1
\end{bmatrix}_{3\times 4}
\qquad
C = \begin{bmatrix}
 1 & 0 & 0 & 0 \\
 0 & 1 & 0 & 0 \\
 0 & 0 & 1 & 0 \\
 0 & 0 & 0 & 1
\end{bmatrix}_{4\times 4}
$$

In [11]:
# Código para Exercício 1
import numpy as np
A = np.full((3,3),8)
B = np.full((3,4),1)
C = np.eye(4)

#D = ((A^t@B) + B)@C^-1
AtB = A.T@B
e = AtB + B
Cinv = np.linalg.inv(C)
D = e@Cinv
print(D)

#Código para o Exercicio 2
Anao = A[:2,:2]
Bnao = B[:2,:2]
Cnao = C[:2,:2]

#Dnao = ((Anao^t@Bnao) + Bnao)@Cnao^-1
AtB = Anao.T@Bnao
e = AtB + Bnao
Cinv = np.linalg.inv(Cnao)
Dnao = e@Cinv
print(Dnao)

[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
[[17. 17.]
 [17. 17.]]


## Questão 2
**2A.** Escreva uma função python que recebe $m$ como entrada e executa os seguintes passos:
1. [ ] gera uma matriz aleatória $W_{m \times 4}$ (função **numpy.random.randn**),
2. [ ] divide cada uma das entradas por $\sqrt{m}$ (salva resultado em $\tilde W$),
3. [ ] calcula $Z = \tilde W^\top \times \tilde W$,
4. [ ] imprime $Z$,
5. [ ] calcula a norma Frobenius da diferença entre $Z$ e a matriz identidade $I_{4 \times 4}$.

In [12]:
# Código para Exercício 2
import math

def questao2(m):
    W = np.random.randn(m,4)
    Wlinha = W/math.sqrt(m)
    Z = Wlinha.T@Wlinha
    print(Z)
    return np.linalg.norm(Z-np.eye(4),'fro')

print(questao2(10))

[[ 1.55366329  0.06642021  0.2486224  -0.12731778]
 [ 0.06642021  1.06149344 -0.26463811  0.24367005]
 [ 0.2486224  -0.26463811  1.156298    0.08649062]
 [-0.12731778  0.24367005  0.08649062  0.59501432]]
0.9682015145200852


**2B.** Qual a norma da diferença obtida para $m=100$? E para $m=10000$?

In [13]:
#Resposta
diferença100 = questao2(100)
diferença10k = questao2(10000)
print("A diferença para m = 100 é {} e para m=10000 é {}".format(diferença100,diferença10k))

[[ 1.1284955   0.04245917  0.07369586 -0.03018181]
 [ 0.04245917  1.17230789  0.11099259  0.04710495]
 [ 0.07369586  0.11099259  0.93089783 -0.17383398]
 [-0.03018181  0.04710495 -0.17383398  1.15564527]]
[[ 1.02941868  0.00394957  0.02012393  0.01566832]
 [ 0.00394957  0.98189197  0.00727636 -0.00586304]
 [ 0.02012393  0.00727636  0.99487952  0.00177926]
 [ 0.01566832 -0.00586304  0.00177926  1.02897391]]
A diferença para m = 100 é 0.4254459279862936 e para m=10000 é 0.059767672567045266


**2C.** O que podemos dizer sobre a matriz $\tilde W$?

Resposta: Wlinha é W normalizado.